before_script:
- npm install -g browserstack-test simple-http-server
- nserver -p 9999 &
env: 
  global: 
  - secure: JyPRwQevSHwJ8+989sucMBlsxXLX29OVmo00yiQJuE638oaPwqzz5AM/JEPOsAVRsHYn+rlAZOeQeS3x3MHyWQTIizi8qCv2aIRfuI6g44GqyntkxYXshgt3ohlRy3CIGTS0miWfDX65pSg5iWyjJn1YPrMg/miGYYmpW7ZVNvo=
  - secure: mvnjzYe7af0qc1HhRBzgO9s3qzDMBHivy64eR/lMLJH+Cb08mFRl4ZLj47QxFMYmi45n+NMNp0uqywZVDnl/Pn1PJSJJUfdjzemNY438BTxsDJ4UZ4VKiqnzLMwe2hyWtm3dOlhrXNhimYUrK8wG37gFdjrxdZK6kkYxT/jpMA0=
  - secure: nJtt9Q0YNRJ4jDk3YazLqXiK0qSqpE3zPeYq93Kl9Kg+ud3vEuCw+JYd3o8rClk15C3u60kbV3MOoivVVPkfoyEmn2t1MxHVX9cu8nZbFJ5Sji52PmK6yhgmbFlIOWfbwsSPu0OmvyFiwLYaehR81AI4nkaraZLfv5IHBtAbNI8=
language: ruby
script: 'rake bstest'
